image: Visual Studio 2022  # بيئة Windows

build_script:
  - ps: |
      # تفعيل RDP
      Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
      Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      
      # تعيين كلمة مرور
      $password = ConvertTo-SecureString "AppVeyorRDP@123" -AsPlainText -Force
      Set-LocalUser -Name "Administrator" -Password $password
      
      # إظهار IP السيرفر
      Write-Host "RDP IP: $(Test-Connection -ComputerName (hostname) -Count 1 | Select -ExpandProperty IPV4Address)"
