image: Visual Studio 2022

build_script:
  - ps: |
      # تثبيت OpenSSH إذا لم يكن مثبتًا (مطلوب لـ Serveo)
      Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0
      
      # تفعيل RDP
      Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
      Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      
      # تعيين كلمة مرور
      $password = ConvertTo-SecureString "MyRDP@123!" -AsPlainText -Force
      Set-LocalUser -Name "Administrator" -Password $password
      
      # تشغيل Serveo لتعريض منفذ RDP (3389)
      Start-Process ssh -ArgumentList "-R 80:localhost:3389 serveo.net" -NoNewWindow -Wait
      
      # إظهار معلومات الاتصال (سيظهر عنوان Serveo في السجلات)
      Write-Host "======================================"
      Write-Host "RDP via Serveo:"
      Write-Host "استخدم هذا العنوان في تطبيق Remote Desktop:"
      Write-Host "serveo.net:3389"
      Write-Host "Username: Administrator"
      Write-Host "Password: MyRDP@123!"
      Write-Host "======================================"
